apiVersion: v1
kind: "Service"
metadata:
  name: hello-v1
  namespace: prom
  labels:
    name: hello-v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  ports:
    - name: hello-v1
      protocol: TCP
      port: 8081
      targetPort: 8081

  selector:
    app: hello-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hello-v1
  name: hello-v1
  namespace: prom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-v1
  template:
    metadata:
      labels:
        app: hello-v1
    spec:
      containers:
        - name: hello-v1
          image: hello:v1
          ports:
            - containerPort: 8081
              protocol: TCP
